name: Vercel Production Deployment
on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Generate environment.ts
        run: |
          mkdir -p FinalProject/src/environments
          cat > FinalProject/src/environments/environment.ts <<EOF
          export const environment = {
            production: true,
            supabaseUrl: '${{ secrets.SUPABASE_URL }}',
            supabaseKey: '${{ secrets.SUPABASE_ANON_KEY }}'
          };
          EOF

      - name: Install dependencies
        working-directory: FinalProject
        run: npm ci

      - name: Build Project Artifacts
        working-directory: FinalProject
        run: npx ng build --configuration production

      - name: Move build output
        run: |
          mkdir -p .vercel/output/static
          ls -la FinalProject/dist/
          cp -r FinalProject/dist/finalProject/browser/* .vercel/output/static/
          cat > .vercel/output/config.json <<EOF
          {
            "version": 3,
            "routes": [
              { "handle": "filesystem" },
              { "src": "/(.*)", "dest": "/index.html" }
            ]
          }
          EOF

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
